name: check-label-actions
on: [pull_request]
jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REPOSITORY
      - run: echo $GITHUB_SHA
      - run: gh api search/issues -f q='is:pr'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
