name: check-label-actions
on: [pull_request]
jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REPOSITORY
      - run: echo $GITHUB_SHA
      - run: echo $GITHUB_REF
      - run: echo $GITHUB_HEAD_REF
      - run: echo $GITHUB_BASE_REF
      - run: gh api -X GET search/issues -f q="repo:$GITHUB_REPOSITORY is:pr"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
