name: check-label-actions
on: [pull_request]
jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: check PR labels
        run: |
          PR_NUM=`echo $GITHUB_REF | sed -e 's/[^0-9]//g'`
          LABELS=`gh api "repos/$GITHUB_REPOSITORY/pulls/$PR_NUM" --jq '.labels'`
          if [ $LABELS = '[]' ]; then
            echo '1つ以上のラベルを設定してください'
            exit(1)
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
