name: check-label-actions
on: [pull_request]
jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - run: PR_NUM=`echo $GITHUB_REF | sed -e 's/[^0-9]//g'`
      - run: echo $PR_NUM
      - run: gh api repos/$GITHUB_REPOSITORY/issues/$PR_NUM
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
