name: check-label-actions
on: [pull_request]
jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - run: |
          PR_NUM=`echo $GITHUB_REF | sed -e 's/[^0-9]//g'`
          echo $PR_NUM
          gh api "repos/$GITHUB_REPOSITORY/pulls/$PR_NUM" --jq '.labels'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
